name: Build Docker Image and Deploy
on:
  push:
    branches:
      - main
    tags:
      - '*'
env:
  IMAGE_NAME: andruwkakz/app_for_diplom
  NAMESPACE: nginx-diplom
  DEPLOYMENT_NAME: nginx-diplom

jobs:
  build-docker-image:
    runs-on: self-hosted
    
    steps:
      # Шаг 1: Клонируем проект
      - name: Checkout Code
        uses: actions/checkout@v4
      
      - name: Determine Docker tag
        run: |
          if [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
            echo "TAG=latest" >> $GITHUB_ENV
          elif [[ "${{ github.ref }}" == refs/tags/* ]]; then
            echo "TAG=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
          fi

      # Шаг 2: Авторизуемся в Docker Registry
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Шаг 3: Собираем Docker образ
      - name: Build Docker Image
        run: docker build -t  ${{ env.IMAGE_NAME }}:${{ env.TAG }} .
     
      # Шаг 5: Пушим Docker образ в Docker Hub
      - name: Push Docker Image
        run: docker push  ${{ env.IMAGE_NAME }}:${{ env.TAG }}